# Generated by Django 5.1.1 on 2024-12-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_video_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='XP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='lvl',
            field=models.IntegerField(default=0),
        ),
    ]
