# Generated by Django 5.1.1 on 2025-04-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.TextField(default='computacion'),
            preserve_default=False,
        ),
    ]
