# Generated by Django 5.1.1 on 2025-04-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_course_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tag',
            field=models.CharField(max_length=100),
        ),
    ]
