# Generated by Django 5.1.1 on 2025-04-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_topicrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicrequest',
            old_name='contend',
            new_name='content',
        ),
        migrations.AddField(
            model_name='topicrequest',
            name='subject',
            field=models.CharField(default='defaulttext', max_length=100),
            preserve_default=False,
        ),
    ]
